pa_charlas_app/urls.py
from os import name
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django.views.decorators.csrf import csrf_exempt

from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from graphene_django.views import GraphQLView

from .views import views, views_avisos
from . import views_rest

rest_router = routers.DefaultRouter()
rest_router.register('participante', views_rest.ParticipanteViewSet, basename='user')
rest_router.register('charla', views_rest.CharlaViewSet, basename='charla')
rest_router.register('texto', views_rest.TextoViewSet)
rest_router.register('charlaitem', views_rest.CharlaItemViewSet)
#A: agregamos las vistas rest al router asi las muestra en la UI

urlpatterns = [
	path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
	path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
	path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
	path('api/token/user/', views_rest.token_user, name='token_user'),
	#A: autenticacion de la api REST o GraphQL

	path('api/', include(rest_router.urls)), #A: api REST

	path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=True))), #A: api graphql

	path("login/", views.login, name="login"),
	path('clave/', login_required(views.UserPassCambiar), name="user_pass_cambiar"),
	path('login/clave/', auth_views.LoginView.as_view(template_name='pa_charlas_app/user_login_form.html'), name="user_login"),

	path("facebook_delete_data/", views.FacebookDataDeletionView.as_view(), name="facebook_delete_data"),
	path("facebook_delete_data_check/<str:code>/", views.FacebookDataDeletionCheckView.as_view(), name="facebook_delete_data_check"),
	#A: login desde la UI web

	path('charla/', views.CharlaQueSigoListView.as_view(), name='charla_quesigo_list' ),
	path('charla/todas', views.CharlaListView.as_view(), name='charla_list' ),
	#A: el alma de la aplicacion son las "charlas"

	path('charla/nueva', login_required(views.texto_edit), name='texto_new'),
	#A: crear una charla es simplemente escribir un texto con hashtags, hay uno automatico para casuales

	path('charla/<int:charla_pk>/nuevo', login_required(views.texto_edit), name='charla_texto_nuevo'),
	path('charla/<str:charla_titulo>/nuevo', login_required(views.texto_edit), name='charla_texto_nuevo_s'),
	path('charla/<int:charla_pk>/<int:pk>', login_required(views.texto_edit), name='charla_texto_edit'),
	#A: las charlas estan hechas de textos

	path('imagen/<str:imagen_titulo>', login_required(views.imagen_edit), name='imagen_edit'),

	path('texto/', views.texto_list, name='texto_list'),

	path('texto/<int:pk>', views.texto_detail, name='texto_detail'),
	path('texto/<int:pk>/img.png', views.texto_img, name='texto_img'),
	#A: hay un link para el texto asi lo compartimos en redes

	path('charla/<int:pk>/', views.charla_texto_list, name='charla_texto_list_k'),
	path('charla/<str:charla_titulo>/', views.charla_texto_list, name='charla_texto_list_t'),
	#A: en general miramos charlas por id o por titulo

	path('evento/', views.evento_list, name='evento_list'),
	path('evento/ical/', views.evento_list_ical, name='evento_list_ical'),
	#A: Agenda de eventos

	path('usuario/', views.usuario_list, name='usuario_list'), #TODO: poner login_required?
	path('usuario/<int:pk>/', views.usuario_texto_list, name='usuario_texto_list_k'), #TODO: poner login_required?
	#A: lista de usuarios

	path('donde-nombran-a/<str:username>/', views.usuario_textos_que_nombran, name='usuario_textos_que_nombran'),
	path('como/', login_required(views.usuario_plan), name='usuario_plan'), 
	path('como/<str:username>/', login_required(views.usuario_plan), name='usuario_plan'), 

	path('banco/',login_required(views.banco_list), name='banco_list'),
	re_path(r't/(?P<un_path>.*)/$', views.CharlaComoPathListView.as_view(), name='charla_como_path'),
	#A: ej. t/sabado/cada_mes para buscar titulos que digan sabado y cada_mes

	path('', views.texto_list, name='home'),
	#A: la home page es la lista de textos nuevos

	#S: Avisos ############################
	path('aviso/', views_avisos.AvisoListView.as_view(), name='aviso_list'),
	path('aviso/<int:pk>/', views_avisos.AvisoDetailView.as_view(), name='aviso_detail'),
	path('aviso/mios/', login_required(views_avisos.AvisoMiosListView.as_view()), name='aviso_user_list'),
	path('aviso/nuevo/', login_required(views_avisos.AvisoFormView.as_view()), name='aviso_new'),
	path('aviso/nuevo/<int:pk>/',login_required(views_avisos.AvisoUpdateView.as_view()), name='aviso_edit'),


]


if settings.IS_DEVEL_SERVER: #A: solo en desarrollo local! sino, configurar ej. nginx
	urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #A: imagenes subidas 

pa_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
	path('admin/', admin.site.urls),

	path('social-auth/', include('social_django.urls', namespace="social")),
	path("logout/", auth_views.LogoutView.as_view(), name="logout"),
	#A: login esta en pa_charlas_app

	path('', include('pa_charlas_app.urls')),
]

pa_charlas_app/models/models_avisos.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User
from pa_charlas_app.models import BaseModel


class AvisoModel(BaseModel):
    """
    Aviso donde se publicaran los servicios que cada usuario ofrece, por ejemplo los seminarios.
    """
    class Meta:
        verbose_name = 'Aviso'
        verbose_name_plural = 'Avisos'

    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    detalle = models.TextField()
    precio = models.FloatField(help_text='Precio del aviso reflejado en PodemosTokens')

    def __str__(self):
        return f'{self.titulo} de {self.autor}, por ${self.precio}'

pa_charlas_app/models/models_base.py
from django.db import models


class BaseModel(models.Model):
    """
    Modelo base del cual van a heredar todos los modelos.
    Te registra la fecha de cuando fue creado y modificado
    Y ademas ejecuta el clean del modelo antes de guardarlo,
    algo que django no hace por defecto.
    """
    class Meta:
        abstract = True
    
    fh_creado = models.DateTimeField(
        'creado a las ',
        auto_now_add=True,
        help_text='Fecha y hora en qeu el modelo fue creado'
    )
    fh_modificado = models.DateTimeField(
        'modificado a las ',
        auto_now=True,
        help_text='Fecha y hora en qeu el modelo fue editado'
    )

    def save(self, *args, **kwargs):
        self.clean()
        super(BaseModel, self).save(*args, **kwargs)

pa_charlas_app/models/models_charlas.py
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404, redirect

from .models_extra import * #A: para que agregue otros lookups como like 
from pa_charlas_app.util import *

import datetime as dt
import re
import hashlib

import logging
logger = logging.getLogger(__name__)

User= get_user_model() #U: la implementacion q este configurada

class Texto(models.Model): #U: cualquier texto que publiquemos, despues especializamos
	de_quien= models.ForeignKey('auth.User', on_delete=models.CASCADE)
	fh_creado= models.DateTimeField(default=timezone.now)
	fh_editado= models.DateTimeField(default=timezone.now)

	titulo= models.CharField(max_length=200)
	texto= models.TextField()

	def __str__(self):
		return f'{self.fh_creado} {self.de_quien} {self.titulo}'

class Imagen(models.Model): #U: las imagenes están en el primer nivel como los textos, despues los conectamos
	de_quien= models.ForeignKey('auth.User', on_delete=models.CASCADE)
	fh_creado= models.DateTimeField(default=timezone.now)

	titulo= models.CharField(max_length=200)
	imagen= models.ImageField() 
	#VER: https://www.geeksforgeeks.org/imagefield-django-models/
	#VER: MEDIA_ROOT en settings.py

class TipoCharla(models.Model): #U: casual, curso, etc.
	titulo= models.CharField(max_length=200, unique=True)

	def __str__(self):
		return self.titulo

class Charla(models.Model): #U: una coleccion de textos sobre algun tema
	de_quien= models.ForeignKey('auth.User', on_delete=models.CASCADE)
	fh_creado= models.DateTimeField(default=timezone.now)

	titulo= models.CharField(max_length=200, unique=True)

	tipo= models.ForeignKey('TipoCharla', on_delete=models.SET_DEFAULT, default=-1)
	textos= models.ManyToManyField(Texto, through='CharlaItem')

	def __str__(self):
		return f'{self.titulo} {self.tipo} {self.fh_creado} {self.de_quien} '

class CharlaItem(models.Model): #U: conecta un texto con una charla
	charla= models.ForeignKey('Charla', on_delete=models.CASCADE)
	texto=  models.ForeignKey('Texto', on_delete=models.CASCADE)
	orden= models.CharField(max_length=50, default='') #U: ordenamos 1ro por esto, despues por fecha
	nivel= models.IntegerField(default=0) #U: 0 es el de siempre, 1 es mas adentro ej. respuesta, 2 es comentario en la respuesta como un hilo en FB, etc.
	

	def __str__(self):
		return f'{self.charla.titulo} {self.texto}'

class Voto(models.Model): #U: Un tipo de voto, ej "Quiero participar"
	titulo= models.CharField(max_length=200, unique=True)

	def __str__(self):
		return f'{self.titulo}'

class VotoItem(models.Model): #U: Un voto que le puso una persona a un texto
	de_quien= models.ForeignKey('auth.User', on_delete=models.CASCADE)
	texto=  models.ForeignKey('Texto', on_delete=models.CASCADE)
	voto= models.ForeignKey('Voto', on_delete=models.CASCADE)
	fh_creado= models.DateTimeField(default=timezone.now)

	class Meta:
		unique_together= [["de_quien","texto" ,"voto"]]
		#A: asegurar que cada terna (de_quien, texto, voto) esta UNA sola vez.

	def __str__(self):
		return f'{self.voto.titulo} {self.de_quien} {self.texto}'

class Visita(models.Model): #U: cuando vio por ultima vez cada charla una usuaria
	charla= models.ForeignKey('Charla', on_delete=models.CASCADE)
	de_quien= models.ForeignKey('auth.User', on_delete=models.CASCADE)
	fh_visita= models.DateTimeField(default=timezone.now)

	class Meta:
		unique_together= [["charla", "de_quien"]]
		#A: asegurar que cada par (de_quien, charla) esta UNA sola vez.

	def __str__(self):
		return f'{self.de_quien.username} {self.charla.titulo} {self.fh_visita}'

# S: funciones comodas ######################################
from pa_charlas_app.hashtags import hashtags_en
def charla_tipo_tema(): #U: por comodidad
	return TipoCharla.objects.get(titulo='Tema')

def charla_tipo_hilo(): #U: por comodidad
	return TipoCharla.objects.get(titulo='Hilo')

def conUserYFecha_guardar(form, user, commit= True):
	ahora= timezone.now() 
	obj= form.save(commit=False)
	de_quien_vacio= (not hasattr(obj,'de_quien')) or (obj.de_quien is None) #A: si no es none, no lanza excepcion y guarda false
	if de_quien_vacio: #A: Si no tiene autor es nuevo 
		obj.de_quien= user
		obj.fh_creado= ahora
	elif obj.de_quien != user: #A: no era el autor! no se lo dejo modificar
		raise PermissionDenied	
	else:
		pass
	
	#A: no debe pasar de aca si no es el duño del objeto	
	if 'fh_editado' in obj.__dict__: 
		obj.fh_editado= ahora
	#A: si tiene un field fh_editado lo actualizamos

	if commit:
		obj.save() #A: guarde el obj actualizado, para poder agregarlo a charlas
	return obj

def charla_titulo_valido(un_string): #U: devuelve un titulo de charla aceptado O None si no tiene arreglo
	if not un_string[0] in '@#':
		un_string= '#'+un_string
	hts= list(hashtags_en(f' {un_string} ', quiere_sin_tildes= False)) #A: nuestras urls y db soportan tildes
	#TODO: mover a hashtags_en , pq por ej. ahora requiere espacios alrededor del titulo y hay que hacer esta chanchada
	print(f'charla_titulo_valido "{un_string}" {hts}')
	if len(hts)>0 and hts[0] == un_string:
		return un_string
	else:
		return None

def charla_agregar_texto(charla_titulo, texto, user, orden= None, charla_tipo= None, nivel = None): #U: agrega el texto a la charla, q crea si es necesario
	puedeModificarEstaCharla= True #DFLT

	charla_titulo= charla_titulo_valido(charla_titulo)
	if charla_titulo is None:
		return False

	m= re.match(r'.*?de_participante_(.*)$',charla_titulo)
	if not m is None: #A: es una charla que solo puede modificar una participante
		puedeModificarEstaCharla= (m.groups(1)[0]	== user.username)

	if puedeModificarEstaCharla:
		chs= Charla.objects.filter(titulo= charla_titulo) 
		if chs.exists(): #A: la charla ya existia
			ch= chs.first() 
		else:
			charla_tipo= charla_tipo_tema() if charla_tipo is None else charla_tipo
			ch= Charla(de_quien= user, titulo= charla_titulo, tipo= charla_tipo)
			ch.de_quien= user
			ch.fh_creado= timezone.now()
			ch.save()	#A: cree una charla nueva, la guardo para poder agregar el texto

	
		texto_id= texto if type(texto)==int else texto.pk
		texto_fh= timezone.now() if type(texto)==int else texto.fh_creado
		#DBG: print(f'TEXTO_ID {texto_id} CHARLA {ch}')
		(chit, loCreoP)= CharlaItem.objects.get_or_create(
			charla= ch,
			texto_id= texto_id
		)
		if not (orden is None): #A: me pasaron un orden ej en una respuesta
			chit.orden= orden
		elif chit.orden is None or chit.orden=='': #A: no me pasaron Y no tenia puesto a mano de antes
			chit.orden= texto_fh.strftime('_%y%m%d%H%M%S')

		if not nivel is None:
			chit.nivel= nivel

		chit.save()

		return True

	return False

def charla_quitar_texto(charla_titulo, texto):
	CharlaItem.objects.filter(	
			charla__titulo= charla_titulo,
			texto= texto
		).delete() #A: si existe para ese dueño lo borra, sino no dice nada

def link_jitsi_para(texto, charla_titulo):
	mhash= hashlib.md5(f'{texto.pk} {texto.de_quien.username} {texto.fh_creado}'.encode('utf-8')).hexdigest()
	#A: un hash para que no se nos metan en la call adivinando PERO que no cambie despues que cree el texto
	tt= charla_titulo[1:] if not charla_titulo is None else texto.de_quien.username
	jitsi_link= f'https://meet.jit.si/pa_{tt}_{mhash}'
	return jitsi_link

def texto_con_juntada_virtual(texto, hashtags, charla_titulo): #U: si texto menciona #juntada_virtual y no hay link, devueve uno con link (no modifica nada, no guarda en la db, solo devuelve texto recomendado)
	resultado= texto.texto #DFLT
	if '#juntada_virtual' in hashtags:
		if 'meet.' in texto.texto or 'zoom.' in texto.texto or 'jit.' in texto.texto:
			#TODO: mejorar el matching de las urls
			pass #A: no hago nada, ya habla de algun servicio de conferencias
		else:
			jitsi_link= link_jitsi_para(texto, charla_titulo)
			resultado= texto.texto.replace('#juntada_virtual', f'#juntada_virtual [en este link]({jitsi_link})')
	return resultado

def hastagCasual(user):
	hashtag= f'#casual{ timezone.now().strftime("%y%m%d%H%M") }{user.username}'
	return hashtag

def texto_guardar(form, user, charla_pk=None, charla_titulo=None, responde_charlaitem_pk= None, orden=None):
	#DBG: print(f'texto_guardar')

	texto= conUserYFecha_guardar(form,user,False) #A: no hago el save. Verifica los permisos.
	#TODO: OjO! Si hay problema con las charlas, el texto se guarda igual. Que hacemos?

	#TODO:SEC no dejar modificar textos de otro user
	if charla_titulo is None and not charla_pk is None:
		ch= Charla.objects.get(pk= charla_pk)
		charla_titulo= ch.titulo

	nivel = 0 #DFTL
	#orden = None #DFLT como parametro
	texto_respondido_id= None #DFLT
	charlaitem_respondido= None #DFLT

	if not responde_charlaitem_pk is None:
		(nivel, orden, texto_respondido_id) = datos_respuesta(responde_charlaitem_pk)

	hts= list(hashtags_en(texto.texto, quiere_sin_tildes= False)) #A: nuestras urls y db soportan tildes
	#DBG: print(f'hashtags {hts} en {texto.texto}')

	if not charla_titulo is None:	
		if not charla_titulo in hts:
			texto.texto += f'\n\n {charla_titulo}'
			hts.append(charla_titulo)
		#A: si venia de una charla, le agrego el hashtag automaticamente, espacio para q no sea titulo markdown
	else:
		hashtag= hastagCasual(user)
		if not hashtag in hts:
			texto.texto += f'\n\n {hashtag}' 
			hts.append(hashtag)
		#A: si no venia de una charla, empieza una casual, espacio para q no sea titulo markdown

	if not texto_respondido_id is None: #A: respondemos a otro texto, agregar al hilo
		hashtag= f'#hilo_{texto_respondido_id}'		
		if not hashtag in hts:
			texto.texto += f'\n\n {hashtag}' 
			hts.append(hashtag)

	#A: agregamos hashtags al texto Y la lista de hashtags, evitando confundir #idea1 con #idea13

	texto.texto= texto_con_juntada_virtual(texto, hts, charla_titulo)
	#A: si mencionaba #juntada_virtual agregamos link, sino queda igual

	logger.info(f'DB TEXTO {user.username} charla={charla_pk} hashtags={hts}')
	texto.save() 

pa_charlas_app/models/models_extra.py
#INFO: agregados al ORM ej expresiones para queries
#VER: https://docs.djangoproject.com/en/3.0/howto/custom-lookups/

from django.db.models import Lookup
from django.db.models.fields import Field

@Field.register_lookup
class Like(Lookup):
	lookup_name = 'like'

	def as_sql(self, compiler, connection):
		lhs, lhs_params = self.process_lhs(compiler, connection)
		rhs, rhs_params = self.process_rhs(compiler, connection)
		params = lhs_params + rhs_params
		return '%s LIKE %s' % (lhs, rhs), params

pa_charlas_app/forms.py
from django import forms

from .models import Texto, Imagen, AvisoModel

class TextoForm(forms.ModelForm):
	class Meta:
		model = Texto
		fields = ('texto',)

class ImagenForm(forms.ModelForm):
	class Meta:
		model = Imagen
		fields = ('imagen',)

class AvisoForm(forms.ModelForm):
	class Meta:
		model = AvisoModel
		exclude = ('autor',) #A: el autor lo voy a tomar del user logueado, no quiero que lo ingrese en el form

pa_charlas_app/templates/pa_charlas_app/base_edit.html
{% extends 'pa_charlas_app/base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h2>{{ titulo }}</h2>
	<form method="POST">{% csrf_token %}
		<input type="hidden" name="url_donde_volver" value="{{ url_donde_volver }}">
		<input type="hidden" name="extra_form_data" value="{{ extra_form_data }}">
		{% bootstrap_form form %}

		{% bootstrap_button 'Guardar'  id='btnGuardar' button_type='submit' %}

		<input type="text" 
			placeholder="Tags y Usuarios" 
			onkeyup="showTagButtons(this.value, '#botonesParaTags', '#id_texto')"
		>

		<a class="btn btn-primary" href="https://es.piliapp.com/symbol/#recents" target="_blank" role="button">
			<span class="fa fa-smile-o"><span class="sr-only">emojis</span></span>
		</a>

		<button type="button" class="btn btn-outline-success ayuda" onclick="ayuda('Sobre los textos',{charla:'ayuda_mensaje',orden:'ayuda_markdown'})">
			<span class="fa fa-question-circle"><span class="sr-only">Agregar a otra charla</span></span>
		</button>

	</form>
	<div id="botonesParaTags"></div>
	<div id="imagenes">
	</div>
{% endblock %}

{% block extra_js%}
	<script>
		const elTexto = document.getElementById('id_texto'); //A: me guardo el textArea
		const elImagenesList = document.getElementById('imagenes'); //A: me guardo el textArea

		//S: este script manda un mensaje de alerta 
		// si estas escribiendo un texto y cerras la ventana sin guardarlo
		const btnGuardar = document.getElementById('btnGuardar');
		let ultimoTextoGuardado = elTexto.value;//A: me guardo el texto que se cargo al incio

		btnGuardar.addEventListener('click',function() {//A: apreto guardar texto
			ultimoTextoGuardado = elTexto.value; //A: actualizo el texto por si el usuario lo modifico
		});

		window.addEventListener('beforeunload', function (e) {//U: captura el evento 'cerrar la ventana'
			if(elTexto.value != ultimoTextoGuardado){ 
				//A: se modifico el texto y el usuario no le dio guardar
				e.preventDefault(); //U: evito que se cierre la ventana
				e.returnValue = '¿Desea salir y perder los cambios?';	
			}
		});

		//S: imagenes en el texto
		var ImagenesDetectadas= {}; //U: para redibujar solo si hay nuevas
		function imagenesDetectarEnTexto(quiereRedibujarSioSi) { //U: busca tags de imagenes en el texto

			const matches= {};
			const txt= elTexto.value;
			const re= /\/deusr\/([a-zA-Z0-9_-]+)\.(png|jpg)/g;
			let m;
			while ( m= re.exec(txt)) { 
				matches[m[0]]= m[1];
			}
			//A: matches tienen las que detecte ahora
			
			const hayAlgunaMenos= Object.keys(ImagenesDetectadas).find(k => matches[k]==null);
			const hayAlgunaMas= Object.keys(matches).find(k => ImagenesDetectadas[k]==null);

			if (hayAlgunaMenos || hayAlgunaMas || quiereRedibujarSioSi) { ImagenesDetectadas= matches;
				console.log("imagenesDetectarEnTexto cambio", ImagenesDetectadas);
				elImagenesList.innerHTML=''; //A: vaciar anteriores
				Object.keys(ImagenesDetectadas).forEach( p => {
					const nombre= ImagenesDetectadas[p];
					const el= $('<div>'); //A: creo nuevo li
					const btn= $('<a>').text(nombre).appendTo(el); //A: con el nombre
					const img= $('<img>').attr({src: p}).css({height: '5em'}).appendTo(el); //A: img con el link
					el.on('click',() => { formSubirImagen(nombre); return false;});
					el.appendTo(elImagenesList); //A: la agrego a la lista
				});
			}
		}

		function formSubirImagenCuandoCierra() {
			console.log('actualizar imagenes');
			imagenesDetectarEnTexto(true);
		}

		function formSubirImagen(titulo) {
			const url= "{% url 'imagen_edit' imagen_titulo='_TITULO_IMAGEN_' %}".replace('_TITULO_IMAGEN_',titulo);
			const wnd= window.open(url, 'PaSubirImagen'); wnd.focus(); //A: nueva ventana si no estaba
			var timer = setInterval(function() { //A: perrito guardian a ver cuando se cierra (onclose no anda)
				if(wnd.closed) { clearInterval(timer);  
					formSubirImagenCuandoCierra();			
				}  
			}, 1000); 
		}

		setInterval(imagenesDetectarEnTexto, 1000); //A: cada 1segundo actualizamos imagenes para subir

	</script>
{% endblock extra_js%}

pa_charlas_app/templates/pa_charlas_app/charla_list.html
{% extends 'pa_charlas_app/base_list.html' %}

{% load bootstrap4 %}

{% block item_titulo %}
	<a href="{% url 'charla_texto_list_k' item.pk %}#nuevo">{{ item.titulo }}</a>
{% endblock %}

{% block item_cuerpo %}
{% endblock %}

{% block item_links %}
{% endblock %}

pa_charlas_app/templates/pa_charlas_app/evento_list.html
{% extends 'pa_charlas_app/base_list.html' %}
{% load pa_charlas_app_extras %}

{% load bootstrap4 %}

{% block resumen %}
	<div class="alert alert-info">
	Podés agregar los eventos autmáticamente a tu calendario de Google, Outlook, Apple con <a href="/evento/ical">este link</a>.
	</div>
{% endblock %}

{% block item_titulo %}
	{{ item.0|date:"l j F y" }}
{% endblock %}

{% block item_cuerpo %}
	{% with k="#"|add:item.1 %}
		{% with textos=charla_a_eventos|at_key:k %}
			{% for texto in textos %}
				<div class="markdown">
{{ texto.texto }}
				</div>
			{% endfor %}
		{% endwith %}
	{% endwith %}
{% endblock %}

{% block item_links %}
{% endblock %}

{% block acciones_sin_item %}
{% endblock %}

pa_charlas_app/templates/pa_charlas_app/login.html
{% extends 'pa_charlas_app/base.html' %}
{% block title %}Sign in{% endblock %}

{% block content %}

{% if request.user.is_authenticated %}
<p>Agregá todas tus redes para vincularlas al mismo nombre de usuario</p>
{% else %}
<p>Para poder escribir y ver más cosas en PodemosAprender necesitás iniciar sesión</p>
<p> Crear cuenta</p>
{% endif %}


<div class="row">
  <div class="col-md-12 social-buttons">
		<div>
			<a class="btn col-md-4 btn-social btn-tumblr" href="{% url "user_login" %}">
				<span class="fa fa-shower"></span> Ingresar con tu clave
			</a>
		</div>

		<div>
			<a class="btn col-md-4 btn-social btn-facebook" href="{% url "social:begin" "facebook" %}">
				<span class="fa fa-facebook"></span> Registrarse con Facebook
			</a>
			{% if "facebook" in redes %} te registraste como {{ redes.facebook }} {% endif %}
		</div>
		
		<div>
			<a class="btn col-md-4 btn-social btn-google" href="{% url "social:begin" "google-oauth2" %}">
				<span class="fa fa-google"></span> Registrarse con Google
			</a>
			{% if "google" in redes %} te registraste como {{ redes.google }} {% endif %}
		</div>
	</div>
</div>
{% endblock %}

pa_charlas_app/templates/pa_charlas_app/p_texto_simple.html
{% load pa_charlas_app_extras %}

{% define '#.*?_de_participante_'|addstr:item.de_quien.username as ht %}
{% define item.texto|re_match:ht|then_sub:'' as texto %}

<div>
	<div id="texto_{{ item.pk }}" class="markdown border-bottom">
{{ texto }} {% comment %} Mantener esta línea pegada al margen izquierdo {% endcomment %}
	</div>
	<div style="text-align: right; font-size: 80%; color: #555;">
		{{ item.fh_editado }}
	</div>
</div>

pa_charlas_app/templates/pa_charlas_app/texto_edit.html
{% extends 'pa_charlas_app/base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h2>Nuevo texto</h2>
	<form method="POST">{% csrf_token %}
		{% bootstrap_form form %}
		{% url 'texto_new' as texto_new_url %}
		{% bootstrap_button 'Guardar' button_type='submit' %}
	</form>
{% endblock %}

pa_charlas_app/templates/pa_charlas_app/user_login_form.html
{% extends 'pa_charlas_app/base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h2>Ingresar con tu clave</h2>
	<form method="POST">{% csrf_token %}
		{% bootstrap_form form %}
		{% bootstrap_button 'Acceder' button_type='submit' %}
	</form>
{% endblock %}